/**
 * Envelope encryption for account-scoped data.
 *
 * - Each account gets a 256-bit data key generated by KMS under the env's
 *   `identity` key; the KMS-wrapped ciphertext is stored on the account row.
 * - Fields are encrypted with AES-256-GCM under the account data key.
 * - Decryption is service-scoped: callers must go through decryptField(s)
 *   with a declared purpose, and EVERY decrypt operation writes an audit
 *   line to the WORM consent-log bucket before the plaintext is returned.
 */
import { createCipheriv, createDecipheriv, randomBytes, randomUUID, createHash } from 'node:crypto';
import { DecryptCommand, GenerateDataKeyCommand } from '@aws-sdk/client-kms';
import { PutObjectCommand } from '@aws-sdk/client-s3';
import { kms, s3 } from './aws.js';
import type { Config } from './config.js';

export interface EnvelopeDeps {
  identityKeyArn: string;
  consentLogBucket: string;
  envName: string;
}

let deps: EnvelopeDeps | undefined;

export function initEnvelope(cfg: Config): void {
  deps = {
    identityKeyArn: cfg.identityKeyArn,
    consentLogBucket: cfg.consentLogBucket,
    envName: cfg.envName,
  };
}

function mustDeps(): EnvelopeDeps {
  if (!deps) throw new Error('envelope crypto not initialised');
  return deps;
}

/** Generate a fresh per-account data key. Returns the KMS-wrapped blob. */
export async function generateAccountDataKey(accountId: string): Promise<Buffer> {
  const d = mustDeps();
  const r = await kms.send(
    new GenerateDataKeyCommand({
      KeyId: d.identityKeyArn,
      KeySpec: 'AES_256',
      EncryptionContext: { account_id: accountId, env: d.envName },
    }),
  );
  if (!r.CiphertextBlob || !r.Plaintext) throw new Error('KMS GenerateDataKey returned no key');
  // We do not keep the plaintext here; encryption paths unwrap on demand.
  return Buffer.from(r.CiphertextBlob);
}

// Short-lived in-memory cache of unwrapped data keys (avoids a KMS call per
// field within one request burst). Audit lines are written per decrypt
// OPERATION (see decryptFields), not per KMS unwrap, so caching does not
// bypass the audit trail.
const keyCache = new Map<string, { key: Buffer; expires: number }>();

async function unwrapDataKey(accountId: string, wrapped: Buffer): Promise<Buffer> {
  const d = mustDeps();
  const cacheKey = createHash('sha256').update(wrapped).digest('hex');
  const hit = keyCache.get(cacheKey);
  if (hit && hit.expires > Date.now()) return hit.key;
  const r = await kms.send(
    new DecryptCommand({
      CiphertextBlob: wrapped,
      EncryptionContext: { account_id: accountId, env: d.envName },
    }),
  );
  if (!r.Plaintext) throw new Error('KMS Decrypt returned no plaintext');
  const key = Buffer.from(r.Plaintext);
  keyCache.set(cacheKey, { key, expires: Date.now() + 5 * 60_000 });
  return key;
}

export async function encryptField(
  accountId: string,
  wrappedKey: Buffer,
  plaintext: string,
): Promise<Buffer> {
  const key = await unwrapDataKey(accountId, wrappedKey);
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const ct = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  return Buffer.concat([iv, cipher.getAuthTag(), ct]); // 12 | 16 | n
}

export interface DecryptContext {
  /** Why the service is decrypting, e.g. 'stage3-mutual-disclosure'. */
  purpose: string;
  /** Who triggered it (account id of the requester, or 'system'). */
  actor: string;
  /** Optional linkage: match id, card id, ... */
  refs?: Record<string, string>;
}

/**
 * Decrypt one or more fields for an account. Writes exactly one WORM audit
 * line for the operation BEFORE returning any plaintext; if the audit write
 * fails, the decrypt fails.
 */
export async function decryptFields(
  accountId: string,
  wrappedKey: Buffer,
  fields: Record<string, Buffer>,
  ctx: DecryptContext,
): Promise<Record<string, string>> {
  const d = mustDeps();
  const auditKey = await writeDecryptAudit(accountId, Object.keys(fields), ctx);
  const key = await unwrapDataKey(accountId, wrappedKey);
  const out: Record<string, string> = {};
  for (const [name, blob] of Object.entries(fields)) {
    const iv = blob.subarray(0, 12);
    const tag = blob.subarray(12, 28);
    const ct = blob.subarray(28);
    const decipher = createDecipheriv('aes-256-gcm', key, iv);
    decipher.setAuthTag(tag);
    out[name] = Buffer.concat([decipher.update(ct), decipher.final()]).toString('utf8');
  }
  void auditKey; // object key returned for callers that want to reference it
  return out;
}

/** Write an audit line to the WORM consent-log bucket. Returns the object key. */
export async function writeDecryptAudit(
  accountId: string,
  fieldNames: string[],
  ctx: DecryptContext,
): Promise<string> {
  const d = mustDeps();
  const now = new Date();
  const key = `decrypt-audit/${d.envName}/${now.toISOString().slice(0, 10)}/${now
    .toISOString()
    .replace(/[:.]/g, '-')}-${randomUUID()}.json`;
  await s3.send(
    new PutObjectCommand({
      Bucket: d.consentLogBucket,
      Key: key,
      ContentType: 'application/json',
      Body: JSON.stringify({
        kind: 'decrypt-audit',
        env: d.envName,
        account_id: accountId,
        fields: fieldNames,
        purpose: ctx.purpose,
        actor: ctx.actor,
        refs: ctx.refs ?? {},
        at: now.toISOString(),
      }),
    }),
  );
  return key;
}

/** Write a consent-event line (opt-ins, human acceptances) to the WORM log. */
export async function writeConsentEvent(event: Record<string, unknown>): Promise<string> {
  const d = mustDeps();
  const now = new Date();
  const key = `consent-events/${d.envName}/${now.toISOString().slice(0, 10)}/${now
    .toISOString()
    .replace(/[:.]/g, '-')}-${randomUUID()}.json`;
  await s3.send(
    new PutObjectCommand({
      Bucket: d.consentLogBucket,
      Key: key,
      ContentType: 'application/json',
      Body: JSON.stringify({ kind: 'consent-event', env: d.envName, at: now.toISOString(), ...event }),
    }),
  );
  return key;
}
